### ISSUE TITLE
Webpack treeshaking cases.

### ISSUE THREAD

**Issue by IWANABETHATGUY** [web-infra-dev/rspack#1006]
## cases/cjs-tree-shaking

- [ ] cases/cjs-tree-shaking/bailouts/
- [ ] cases/cjs-tree-shaking/cjs-to-esm/
- [ ] cases/cjs-tree-shaking/esModule-getter/
- [ ] cases/cjs-tree-shaking/esm-to-cjs/
- [ ] cases/cjs-tree-shaking/exports/
- [ ] cases/cjs-tree-shaking/importing/
- [ ] cases/cjs-tree-shaking/mjs/
- [ ] cases/cjs-tree-shaking/mutate/
- [ ] cases/cjs-tree-shaking/namespace/
- [ ] cases/cjs-tree-shaking/non-root-this/
- [ ] cases/cjs-tree-shaking/object-define-property-replace/
- [ ] cases/cjs-tree-shaking/objects/
- [ ] cases/cjs-tree-shaking/parsing/
- [ ] cases/cjs-tree-shaking/reexports/
- [ ] cases/cjs-tree-shaking/transpiled/
- [ ] cases/cjs-tree-shaking/weird-names/

## cases/inner-graph
- [x] #1024
- [x] #1025
- [ ] 
- [ ] cases/inner-graph/class-dynamic-props/
- [x] #1535
- [ ] cases/inner-graph/extend-class/
- [ ] cases/inner-graph/extend-class2/
- [x] #1392
- [ ] cases/inner-graph/pure-in-removed/
- [x] #1536
- [ ] cases/inner-graph/simple/
- [ ] cases/inner-graph/static-of-class/
- [x] #1537
- [x] #1393

## cases/optimize
- [ ] cases/optimize/side-effects-all-chain-unused/
- [x] cases/optimize/side-effects-all-used/
- [ ] cases/optimize/side-effects-immediate-unused/
- [ ] cases/optimize/side-effects-reexport-start-unknown/
- [ ] cases/optimize/side-effects-root-unused/
- [ ] cases/optimize/side-effects-scope-hoisting/
- [x] cases/optimize/side-effects-simple-unused/
- [ ] cases/optimize/side-effects-transitive-unused/
- [ ] cases/optimize/tree-shaking-commonjs/
- [ ] cases/optimize/tree-shaking-star/
- [ ] cases/optimize/tree-shaking-star2/
