### ISSUE TITLE
Tracking issue of HTML plugin

### ISSUE THREAD

**Issue by h-a-n-a** [web-infra-dev/rspack#1150]
## Our JS HTML plugin

- [x] https://github.com/speedy-js/rspack/issues/1121
- [x] https://github.com/speedy-js/rspack/issues/924
- [x] https://github.com/speedy-js/rspack/issues/1005

## HTMLWebpackPlugin Integration

napi related.
