### ISSUE TITLE
Meta: Open Source Friendly

### ISSUE THREAD

**Issue by Boshen** [web-infra-dev/rspack#1740]
- [x] Disclaimers - What to expect from this project?
- [x] Project goals - Why does this project exist? What are our goals?
- [ ] Communication channels
- [x] Project management - issue / pr templates, labels
- [ ] Milestones
- [ ] Hosted API docs (both Rust and Node)
- [x] Bench table
- [x] Compatibility table
- [ ] Onboarding docs - how to run and debug the project
- [x] Contribution Guides
- [ ] Improve SEO (google)
