### ISSUE TITLE
[Tracking issue] vue support 

### ISSUE THREAD

**Issue by hardfist** [web-infra-dev/rspack#2350]
This issue is used to tracking Vue support.

```[tasklist]
### Vue-loader
- [ ] https://github.com/web-infra-dev/rspack/issues/2351
- [ ] https://github.com/web-infra-dev/rspack/issues/1749
- [ ] https://github.com/web-infra-dev/rspack/issues/2394
- [ ] https://github.com/web-infra-dev/rspack/issues/2646
```

**Comment by g-plane** [comment]
How about Vue JSX? There's an existing SWC plugin for transforming Vue JSX.

**Comment by hardfist** [comment]
> How about Vue JSX? There's an existing SWC plugin for transforming Vue JSX.
supported now

**Comment by g-plane** [comment]
That's a Babel plugin, if I remember. It will gain performance boost if we integrate that SWC plugin into Rspack.

**Comment by hardfist** [comment]
does SWC have vue plugin now ?

**Comment by hardfist** [comment]
so it could be used in swc-loader?

**Comment by g-plane** [comment]
It could, but I hope it can be integrated at Rust-side. That's because, loading plugins as WebAssembly can be slow because of communication between Rust/native code and WebAssembly. If we integrate in Rspack, there won't be communication overhead.

**Comment by chenjiahan** [comment]
@g-plane `swc-plugin-vue-jsx` looks great, does it pass all unit tests of `@vue/babel-plugin-jsx`? Maybe Rspack should integrate this plugin when it is stable enough and verified in some real projects.

**Comment by g-plane** [comment]
All unit test cases are copied from `@vue/babel-plugin-jsx`. Also, it has additional tests which `@vue/babel-plugin-jsx` doesn't have.

**Comment by chenjiahan** [comment]
Sorry I didn't find the tests files, where can I find them?

**Comment by chenjiahan** [comment]
Awesome, I think I'll try compiling [Vant](https://github.com/youzan/vant) with SWC in the near future and give some feedback.

**Comment by h-a-n-a** [comment]
Closed as all tracking issues had been completed.
