### ISSUE TITLE
[Tracking issue] support incremental rebuild

### ISSUE THREAD

**Issue by jerrykingxyz** [web-infra-dev/rspack#2361]
Rspack currently only [supports incremental rebuild in the `make` stage](https://github.com/web-infra-dev/rspack/pull/1629), which provides a huge speed boost. This issue is used to track other remaining incremental rebuilds.

For the support of this feature, the following points need to be completed in every step.
- unify side effects to the top level of process functions, e.g editing the `compliation` property
- partial run against modified file

Support for incremental rebuild in the main steps of the seal stage is as follows
- [ ] code splitting and bundle splitting
- [ ] tree shaking
- [ ] calc module id and chunk id
- [ ] code generation
- [ ] runtime requirements
- [ ] create hash for chunk
- [ ] create chunk assets
- [ ] process assets
- [x] #3153

**Comment by hardfist** [comment]
close for stale
