### ISSUE TITLE
[Tracking Issue] Gatsby support

### ISSUE THREAD

**Issue by ahabhgk** [web-infra-dev/rspack#2365]
This issue is used to tracking Gatsby support

https://github.com/gatsbyjs/gatsby/pull/37732

```[tasklist]
# Gatsby support

- [ ] https://github.com/web-infra-dev/rspack/issues/2366
- [ ] https://github.com/web-infra-dev/rspack/issues/2368
- [ ] https://github.com/web-infra-dev/rspack/issues/2370
- [ ] https://github.com/web-infra-dev/rspack/issues/2371
- [ ] https://github.com/web-infra-dev/rspack/issues/2372
- [ ] compatibility for gatsby static-query-mapper.ts
```

**Comment by hardfist** [comment]
don't have plan to support gatsby in near future, so close it
