### ISSUE TITLE
[Tracking]: E2E test

### ISSUE THREAD

**Issue by jerrykingxyz** [web-infra-dev/rspack#2410]
This issue is used to tracking e2e test

```[tasklist]
## E2E test
- [ ] https://github.com/web-infra-dev/rspack/issues/2411
- [ ] https://github.com/web-infra-dev/rspack/issues/2413
- [ ] https://github.com/web-infra-dev/rspack-dev-guide/pull/21
- [ ] https://github.com/web-infra-dev/rspack/pull/3664
```
