### ISSUE TITLE
[Tracking Issue] Build infra 

### ISSUE THREAD

**Issue by IWANABETHATGUY** [web-infra-dev/rspack#2472]
## Common
```[tasklist]
- [ ] https://github.com/web-infra-dev/rspack/issues/3135
- [ ] https://github.com/web-infra-dev/rspack/issues/2915
```
## Optimize CI/CD experience
```[tasklist]
- [ ] https://github.com/web-infra-dev/rspack/issues/2916
- [ ] https://github.com/web-infra-dev/rspack/issues/2475
- [x] Optimize CI caching so there's always a warm cache available
- [x] fix crashes in debug mode
- [ ] https://github.com/web-infra-dev/rspack/issues/2497
- [ ] https://github.com/web-infra-dev/rspack/issues/2502
```
## Automatic CI workflow
```[tasklist]
- [ ] https://github.com/web-infra-dev/rspack/pull/3065
- [ ] https://github.com/web-infra-dev/rspack/issues/2483
```
## Release workflow
```[tasklist]
- [ ] https://github.com/web-infra-dev/rspack/issues/2484
- [ ] https://github.com/web-infra-dev/rspack/issues/2583
```

**Comment by Boshen** [comment]
What should be our strategy for upgrading swc? Here are the problems we have so far:
* duplicated deps
* uncertainty on breaking change when upgrade

**Comment by Boshen** [comment]
Most tasks are done for the iteration plan. Closing.
