### ISSUE TITLE
[Tracking issue] Test infra

### ISSUE THREAD

**Issue by IWANABETHATGUY** [web-infra-dev/rspack#2485]
## Webpack test case migration
```[tasklist]
- [ ] https://github.com/web-infra-dev/rspack/issues/2496
- [ ] Webpack test case Alignment
```
## HMR E2E testing
```[tasklist]
- [ ] E2E testing with HMR
- [ ] https://github.com/web-infra-dev/rspack/issues/2410
- [ ] E2E test about create rspack@latest
```
## fine-grained benchmark
```[tasklist]
- [ ] https://github.com/web-infra-dev/rspack/issues/3349
- [ ] Targeted benchmark, such as large repositories with special topologies, for testing bundle-splitting performance regressions
- [ ] cases that have a lot of IO operation - [https://github.com/mui/material-ui](https://github.com/mui/material-ui)
- [x] webpack matrix bench like
- [x] modern-js testing
- [ ] Add benchmark about startup to page active
- [ ] Add bench history about node binding binary size
```
## Optimize testing DX
```[tasklist]
- [ ] Optimizing the use of the rust snapshot testing tool
- [ ] Jest unit testing rust debugging experience optimization
- [ ] https://github.com/web-infra-dev/rspack/issues/3118
- [ ] https://github.com/web-infra-dev/rspack/issues/2609
```

**Comment by zackarychapple** [comment]
Is this also the proper holding issue for integration tests with other tooling and their integration tests to ensure ecosystem compatibility? I'm thinking something like kicking off the Nx Rspack test suite to get signals for regression.
