### ISSUE TITLE
[Tracking issue]: Align loader with webpack

### ISSUE THREAD

**Issue by h-a-n-a** [web-infra-dev/rspack#2645]
```[tasklist]
- [ ] https://github.com/web-infra-dev/rspack/issues/2643
- [ ] https://github.com/web-infra-dev/rspack/issues/1749
- [ ] https://github.com/web-infra-dev/rspack/issues/2646
- [ ] https://github.com/web-infra-dev/rspack/issues/2650
```

**Comment by hyf0** [comment]
All tasks are finished :).
