### ISSUE TITLE
[Tracking]: Related to the FS project

### ISSUE THREAD

**Issue by hyf0** [web-infra-dev/rspack#2694]
### What subject does this issue tracking?

#  Related to the FS project

```[tasklist]
### Tasks
- [ ] https://github.com/web-infra-dev/rspack/issues/2695
- [ ] https://github.com/web-infra-dev/rspack/issues/2696
- [ ] https://github.com/web-infra-dev/rspack/issues/2697
- [ ] https://github.com/web-infra-dev/rspack/issues/2750
- [ ] https://github.com/web-infra-dev/rspack/issues/2751
- [ ] https://github.com/web-infra-dev/rspack/issues/2800
- [ ] https://github.com/web-infra-dev/rspack/issues/2909
- [ ] https://github.com/web-infra-dev/rspack/issues/2924
- [ ] https://github.com/web-infra-dev/rspack/issues/2923
- [ ] https://github.com/web-infra-dev/rspack/issues/2922
- [ ] https://github.com/web-infra-dev/rspack/issues/3277
```

**Comment by hardfist** [comment]
this should be closed and tracked in internal kanban
