### ISSUE TITLE
[Tracking]: Optimize bundle size

### ISSUE THREAD

**Issue by IWANABETHATGUY** [web-infra-dev/rspack#2853]
### What subject does this issue tracking?

# [Subject]

```[tasklist]
### Tasks
- [ ] https://github.com/web-infra-dev/rspack/issues/4817
- [x] concatenateModules
- [x] introduce __webpack_require__.d
- [ ] https://github.com/web-infra-dev/rspack/issues/2941
```

**Comment by Boshen** [comment]
I'm interested in these problems 🙌 Can you walk me through some of these when you are free?

**Comment by IWANABETHATGUY** [comment]
`__webpack_require__.d` is done in favor of custom runtime.

**Comment by IWANABETHATGUY** [comment]
concatenateModules actually is scope hoisting
## mangleExports
e.g.
```js
// index.js
import {abcdefghijk} from './a';
abcdefghijk();
// a.js
export const abcdefghijk = () => {};
export default function() {} 
```
**without mangleExports**

```js
/******/ (() => { // webpackBootstrap
/******/ 	"use strict";
/******/ 	var __webpack_modules__ = ({

/***/ "./basic/a.js":
/***/ ((__unused_webpack_module, __webpack_exports__, __webpack_require__) => {

/***/ ((__unused_webpack_module, __webpack_exports__, __webpack_require__) => {

/* harmony export */ __webpack_require__.d(__webpack_exports__, {
/* harmony export */   abcdefghijk: () => (/* binding */ abcdefghijk)
/* harmony export */ });
const abcdefghijk = () => {};
/* harmony default export */ function __WEBPACK_DEFAULT_EXPORT__() {} 


/***/ })

/******/ 	});
// ... skiping some runtime code
(() => {
/* harmony import */ var _a__WEBPACK_IMPORTED_MODULE_0__ = __webpack_require__("./basic/a.js");

(0,_a__WEBPACK_IMPORTED_MODULE_0__.abcdefghijk)();

})();

/******/ })()
;

```
**with mangleExports**
Only see those import part
```diff
/***/ ((__unused_webpack_module, __webpack_exports__, __webpack_require__) => {

/* harmony export */ __webpack_require__.d(__webpack_exports__, {
- /* harmony export */   abcdefghijk: () => (/* binding */ abcdefghijk)
+ /* harmony export */   V: () => (/* binding */ abcdefghijk)
/* harmony export */ });
const abcdefghijk = () => {};
/* harmony default export */ function __WEBPACK_DEFAULT_EXPORT__() {} 


/***/ })
// skipping some code 
- (0,_a__WEBPACK_IMPORTED_MODULE_0__.abcdefghijk)();
+ (0,_a__WEBPACK_IMPORTED_MODULE_0__/* .abcdefghijk */ .V)();
```

**Comment by IWANABETHATGUY** [comment]
## concatenateModule
By default, generated code of webpack contains a lot of extra runtime code, something like `__webpack_require__`, etc.
 if you enable `concatenateModule`, rspack will try to merge those modules as much as possible(for more bailout conditions you could refer to https://webpack.js.org/plugins/module-concatenation-plugin/#optimization-bailouts)

 I use the same example above, the output should be: 
 
 ```js
 /******/ (() => { // webpackBootstrap
/******/ 	"use strict";

;// CONCATENATED MODULE: ./basic/a.js
const abcdefghijk = () => {};
/* harmony default export */ function a() {} 

;// CONCATENATED MODULE: ./basic/index.js

abcdefghijk();

/******/ })()
;

 ```

**Comment by javaxiu** [comment]
same issue here, the minimal repo : https://github.com/javaxiu/rspac-vs-webpack
after `npm run build; ll -ls ./dist`, we got
```
 142K Oct 27 17:51 rspack_output.js
 99K Oct 27 17:48 webpack_output.js
```
