### ISSUE TITLE
[Tracking]: support `ReactFlight`

### ISSUE THREAD

**Issue by hyf0** [web-infra-dev/rspack#3051]
Currently, this is **not an official guarantee of the Rspack team** but my personal interest. 

---

## Must have

```[tasklist]
### Tasks
- [x] `Dependency#dependency_type` support custom type by third-party plugin
- [ ] Missing `compilation.parser` hook in rust
- [ ] expose options to enable `exports` analyze
- [ ] https://github.com/web-infra-dev/rspack/issues/3070
- [ ] custom module runtime
```

## Has workaround

```[tasklist]
### Tasks
- [ ] Missing `Compilation.dependencyFactories` hook in rust
- [ ] Introduce `AsyncDependenciesBlock` abstraction
- [ ] Align `ResolverFactory#get` with Webpack https://github.com/web-infra-dev/rspack/issues/1547
```

## Codebase

```[tasklist]
### Tasks
- [ ] runtime checking that `AstPath` should not be empty
```

**Comment by hardfist** [comment]
close for inactive

**Comment by hardfist** [comment]
we will revisit this in the future when we're ready
