### ISSUE TITLE
[Tracking]: Webpack conformance tests

### ISSUE THREAD

**Issue by hardfist** [web-infra-dev/rspack#3243]
# [Subject]
tracking test coverage of webpack tests

```[tasklist]
### Runtime @underfin @hyf0 
- [ ] https://github.com/web-infra-dev/rspack/issues/3359
- [ ] amd https://github.com/web-infra-dev/rspack/tree/main/webpack-test/cases/amd
- [ ] async module https://github.com/web-infra-dev/rspack/tree/main/webpack-test/cases/async-modules
- [ ] cjs-interop https://github.com/web-infra-dev/rspack/tree/main/webpack-test/cases/cjs-interop/non-existing-export
- [ ] import.meta https://github.com/web-infra-dev/rspack/tree/main/webpack-test/cases/esm/import-meta
- [ ] nonce https://github.com/web-infra-dev/rspack/tree/main/webpack-test/cases/nonce
- [ ] https://github.com/web-infra-dev/rspack/tree/main/webpack-test/configCases/runtime
```

```[tasklist]
### Module @h-a-n-a @hardfist 
- [ ]  var https://github.com/web-infra-dev/rspack/tree/main/webpack-test/cases/entry-inline
- [ ] json module  https://github.com/web-infra-dev/rspack/tree/main/webpack-test/cases/json
- [ ] big assets https://github.com/web-infra-dev/rspack/tree/main/webpack-test/cases/large
- [ ] mjs https://github.com/web-infra-dev/rspack/tree/main/webpack-test/cases/mjs
- [ ] https://github.com/web-infra-dev/rspack/tree/main/webpack-test/cases/wasm
- [ ] asset https://github.com/web-infra-dev/rspack/tree/main/webpack-test/configCases/additional-pass/simple
- [ ] asset emitted https://github.com/web-infra-dev/rspack/tree/main/webpack-test/configCases/asset-emitted/normal
- [ ] asset modules https://github.com/web-infra-dev/rspack/tree/main/webpack-test/configCases/asset-modules
- [ ] asset url https://github.com/web-infra-dev/rspack/tree/main/webpack-test/configCases/asset-url
- [ ] delete asset https://github.com/web-infra-dev/rspack/tree/main/webpack-test/configCases/assets/delete-asset
- [ ] https://github.com/web-infra-dev/rspack/tree/main/webpack-test/configCases/code-generation
- [ ] https://github.com/web-infra-dev/rspack/tree/main/webpack-test/configCases/custom-modules
- [ ] target https://github.com/web-infra-dev/rspack/tree/main/webpack-test/configCases/ecmaVersion
- [ ] https://github.com/web-infra-dev/rspack/tree/main/webpack-test/configCases/json/tree-shaking-default
- [ ] https://github.com/web-infra-dev/rspack/tree/main/webpack-test/configCases/node
- [ ] https://github.com/web-infra-dev/rspack/blob/main/webpack-test/configCases/require/module-require/index.js
- [ ] https://github.com/web-infra-dev/rspack/tree/main/webpack-test/configCases/wasm
- [ ] https://github.com/web-infra-dev/rspack/tree/main/webpack-test/configCases/web
- [ ] https://github.com/web-infra-dev/rspack/tree/main/webpack-test/configCases/worker
- [ ] https://github.com/web-infra-dev/rspack/tree/main/webpack-test/configCases/node
```

```[tasklist]
### Externals @hardfist 
- [ ] externals https://github.com/web-infra-dev/rspack/tree/main/webpack-test/configCases/externals
```

```[tasklist]
### Code Splitting & Bundle Splitting @hyf0 @h-a-n-a 
- [ ] https://github.com/web-infra-dev/rspack/tree/main/webpack-test/configCases/async-commons-chunk
- [ ] https://github.com/web-infra-dev/rspack/tree/main/webpack-test/configCases/chunk-graph
- [ ] https://github.com/web-infra-dev/rspack/tree/main/webpack-test/configCases/chunk-index/order-multiple-entries
- [ ] https://github.com/web-infra-dev/rspack/tree/main/webpack-test/configCases/graph
- [ ] https://github.com/web-infra-dev/rspack/tree/main/webpack-test/configCases/split-chunks-common
- [ ] https://github.com/web-infra-dev/rspack/tree/main/webpack-test/configCases/split-chunks
```

```[tasklist]
### Errors
- [ ] Errors https://github.com/web-infra-dev/rspack/tree/main/webpack-test/cases
```

```[tasklist]
### Library @underfin @jerrykingxyz
- [ ] experiments.topLevelAwait. https://github.com/web-infra-dev/rspack/tree/main/webpack-test/configCases/async-library
- [ ] https://github.com/web-infra-dev/rspack/tree/main/webpack-test/configCases/library
- [x] https://github.com/web-infra-dev/rspack/tree/main/webpack-test/configCases/output-module
- [x] https://github.com/web-infra-dev/rspack/tree/main/webpack-test/configCases/umd/issue-15545
- [ ] entry library  https://github.com/web-infra-dev/rspack/tree/main/webpack-test/configCases/library/0-create-library
- [ ] target config is not align webpack, eg. node14. https://github.com/web-infra-dev/rspack/tree/main/webpack-test/configCases/output-module/check-defaults
- [ ] __nested_webpack_require_ & amd https://github.com/web-infra-dev/rspack/tree/main/webpack-test/configCases/library/1-use-library
```

--------------

```[tasklist]
### Treeshaking @IWANABETHATGUY @jerrykingxyz @hyf0 
- [ ] cjs treeshaking https://github.com/web-infra-dev/rspack/tree/main/webpack-test/cases/cjs-tree-shaking
- [ ] innerGraph https://github.com/web-infra-dev/rspack/tree/main/webpack-test/cases/inner-graph
- [ ] side effect https://github.com/web-infra-dev/rspack/tree/main/webpack-test/cases/optimize
- [ ] https://github.com/web-infra-dev/rspack/tree/main/webpack-test/configCases/side-effects
```
```[tasklist]
### Resolve @Boshen @hardfist
- [x] https://github.com/web-infra-dev/rspack/tree/main/webpack-test/cases/entry-exports-field
- [ ] https://github.com/web-infra-dev/rspack/tree/main/webpack-test/configCases/resolve
- [ ] https://github.com/web-infra-dev/rspack/tree/main/webpack-test/configCases/resolve-merging/override
- [ ] https://github.com/web-infra-dev/rspack/tree/main/webpack-test/configCases/resolving
```

```[tasklist]
### Loader @ahabhgk @h-a-n-a 
- [ ] https://github.com/web-infra-dev/rspack/tree/main/webpack-test/configCases/loader-import-module
- [ ] loader https://github.com/web-infra-dev/rspack/tree/main/webpack-test/cases/loaders
- [ ] https://github.com/web-infra-dev/rspack/tree/main/webpack-test/configCases/module-name/different-issuers-for-same-module
- [ ] https://github.com/web-infra-dev/rspack/tree/main/webpack-test/configCases/race-conditions/load-module
- [ ] https://github.com/web-infra-dev/rspack/tree/main/webpack-test/configCases/rule-set
```

```[tasklist]
### Cache @jerrykingxyz
- [x] https://github.com/web-infra-dev/rspack/tree/main/webpack-test/configCases/cache-dependencies
```

```[tasklist]
### Misc @9aoy @underfin 
- [ ] https://github.com/web-infra-dev/rspack/tree/main/webpack-test/configCases/clean
- [ ] https://github.com/web-infra-dev/rspack/tree/main/webpack-test/configCases/output
- [ ] https://github.com/web-infra-dev/rspack/tree/main/webpack-test/configCases/simple
```
```[tasklist]
### CSS @ahabhgk
- [ ] https://github.com/web-infra-dev/rspack/tree/main/webpack-test/configCases/css
- [ ] https://github.com/web-infra-dev/rspack/tree/main/webpack-test/configCases/loader-import-module/css
```
```[tasklist]
### Hash @ahabhgk
- [ ] configCases/custom-hash-function/xxhash: custom hash function will hurt performance
- [ ] configCases/contenthash/assets: function type asset generator publicPath is not supported yet, blocked by a bug https://github.com/web-infra-dev/rspack/issues/3465
- [ ] configCases/contenthash/include-chunk-id: blocked by `optimization.chunkIds`
- [ ] configCases/hash-length
```
```[tasklist]
### Sourcemap @ahabhgk 
- [ ] https://github.com/web-infra-dev/rspack/tree/main/webpack-test/configCases/devtools
- [ ] https://github.com/web-infra-dev/rspack/tree/main/webpack-test/configCases/source-map
```
```[tasklist]
### Plugin & Hooks & API @IWANABETHATGUY
- [x] https://github.com/web-infra-dev/rspack/tree/main/webpack-test/configCases
- [ ] https://github.com/web-infra-dev/rspack/tree/main/webpack-test/configCases/process-assets/html-plugin
- [ ] https://github.com/web-infra-dev/rspack/issues/3360
- [ ] https://github.com/web-infra-dev/rspack/tree/main/webpack-test/configCases/rebuild
```
```[tasklist]
### Watch @jerrykingxyz 
- [ ] https://github.com/web-infra-dev/rspack/tree/main/webpack-test/watchCases
```
```[tasklist]
### HMR @jerrykingxyz 
- [ ] https://github.com/web-infra-dev/rspack/tree/main/webpack-test/hotCases
- [ ] https://github.com/web-infra-dev/rspack/tree/main/webpack-test/hotPlayground
```

**Comment by Boshen** [comment]
To quickly get all the blocking issues:

1. Remove the filter

https://github.com/web-infra-dev/rspack/blob/d9dc6b35ec5126ff4ac11130997c4390135f01bb/webpack-test/TestCases.template.js#L61-L75

2.
```
cd webpack-test
FORCE_COLOR=false  pnpm run test --noStackTrace 2> output
```

3. Sort the messages in output ... you'll know which ones are blocking.

**Comment by Boshen** [comment]
First round of issues:

* #3328
* #3330
* #3331
* #3332
* #3333
