### ISSUE TITLE
[Tracking]: Support for builtin swc-loader

### ISSUE THREAD

**Issue by h-a-n-a** [web-infra-dev/rspack#3309]
### What subject does this issue tracking?

# [Subject]

```[tasklist]
### Tasks
- [ ] https://github.com/web-infra-dev/rspack/discussions/3572
- [ ] https://github.com/web-infra-dev/rspack/issues/3278
- [ ] https://github.com/web-infra-dev/rspack/issues/1751
- [ ] https://github.com/web-infra-dev/rspack/issues/3310
- [ ] https://github.com/web-infra-dev/rspack/issues/3311
- [ ] https://github.com/web-infra-dev/rspack/issues/3067
- [ ] https://github.com/web-infra-dev/rspack/issues/3451
```

**Comment by suxin2017** [comment]
https://github.com/web-infra-dev/rspack/pull/3382/files
Do you want to do this loader? It feels weird to write

**Comment by h-a-n-a** [comment]
> https://github.com/web-infra-dev/rspack/pull/3382/files Do you want to do this loader? It feels weird to write

Basically, yes and there will be other tweaks listed above.

**Comment by h-a-n-a** [comment]
Related: https://github.com/web-infra-dev/rspack/discussions/3572

**Comment by chenjiahan** [comment]
Closed because most of related issues has been resolved. Feel free to reopen it if it is needed.
