### ISSUE TITLE
[Tracking]: context module test

### ISSUE THREAD

**Issue by underfin** [web-infra-dev/rspack#3359]
### What subject does this issue tracking?

# [Subject]
 
Here has some context module not support, other test already migrated. see https://github.com/web-infra-dev/rspack/tree/main/packages/rspack/tests/cases/context

```[tasklist]
### Tasks
- [ ] https://github.com/web-infra-dev/rspack/issues/4305
- [ ] https://github.com/web-infra-dev/rspack/issues/4328
- [ ] https://github.com/web-infra-dev/rspack/issues/4329
- [ ] webpack-test/cases/parsing/issue-7778
- [ ] https://github.com/web-infra-dev/rspack/issues/4397
- [ ] https://github.com/web-infra-dev/rspack/issues/4420
- [ ] https://github.com/web-infra-dev/rspack/issues/4429
```
