### ISSUE TITLE
[Tracking] Plugin & Hooks configCases/plugins

### ISSUE THREAD

**Issue by IWANABETHATGUY** [web-infra-dev/rspack#3360]
```[tasklist]
- [ ] https://github.com/web-infra-dev/rspack/issues/3580
- [ ] banner-plugin-hashing
- [ ] https://github.com/web-infra-dev/rspack/issues/3581
- [ ] define-plugin-bigint
- [ ] https://github.com/web-infra-dev/rspack/issues/3602
- [ ] lib-manifest-plugin
- [ ] https://github.com/web-infra-dev/rspack/issues/3606
- [ ] min-chunk-size
- [ ] mini-css-extract-plugin
- [ ] profiling-plugin
- [ ] progress-plugin
- [ ] provide-plugin
- [ ] source-map-dev-tool-plugin
- [ ] source-map-dev-tool-plugin~append
- [ ] https://github.com/web-infra-dev/rspack/issues/3639
```

**Comment by IWANABETHATGUY** [comment]
Some notes, 
1. define plugin need `parser` hooks which will introduce a lot performance overhead, also we already have builtins `define`

**Comment by hardfist** [comment]
close for stale
