### ISSUE TITLE
[Tracking]: completeness of Rspack configuration schema

### ISSUE THREAD

**Issue by hyf0** [web-infra-dev/rspack#3436]
### What subject does this issue tracking?

After #3378, there are still some fields of  Rspack configuration that are loose, we should make them complete.

```[tasklist]
### Tasks
- [ ] https://github.com/web-infra-dev/rspack/issues/3437
- [ ] https://github.com/web-infra-dev/rspack/issues/3438
- [ ] https://github.com/web-infra-dev/rspack/issues/3439
- [ ] https://github.com/web-infra-dev/rspack/issues/3440
- [ ] https://github.com/web-infra-dev/rspack/issues/3441
```

# Guidance

## Missing parts

You could find these loose fields at

https://github.com/web-infra-dev/rspack/blob/33dd6197829c2030be4755ef4f1d3cef03d003e9/packages/rspack/src/config/zod/index.ts#L42-L48

## Process

1. Pick a field(see the tasklist above) that you want to deal with
2. Write them as I did at https://github.com/web-infra-dev/rspack/blob/3ea1fe0f80e83c8cd5490b7d5c3504ed06aeb990/packages/rspack/src/config/zod/index.ts#L20
3. You could write the schema by following the `type` defined at https://github.com/web-infra-dev/rspack/blob/main/packages/rspack/src/config/types.ts#L103.

For example, you could refer to 

https://github.com/web-infra-dev/rspack/blob/33dd6197829c2030be4755ef4f1d3cef03d003e9/packages/rspack/src/config/types.ts#L103

for writing schema of `output`

4. Remove the rewritten field at https://github.com/web-infra-dev/rspack/blob/3ea1fe0f80e83c8cd5490b7d5c3504ed06aeb990/packages/rspack/src/config/zod/_rewrite.ts#L17-L24

For example, if you finish the `output` field, you could just delete this line

https://github.com/web-infra-dev/rspack/blob/3ea1fe0f80e83c8cd5490b7d5c3504ed06aeb990/packages/rspack/src/config/zod/_rewrite.ts#L18

## zod

zod introduction: https://zod.dev/?id=introduction
