### ISSUE TITLE
[Tracking]: Diagnostics

### ISSUE THREAD

**Issue by h-a-n-a** [web-infra-dev/rspack#3459]
### What subject does this issue tracking?

As time goes by, we have met some problems related to error handling. We want to improve the DX for both ourselves and our users.

Therefore, we plan to refactor the error-handling parts of Rspack in every aspect, these include, for example:

* Better error diagnostics
* Report the "how" and "why" when something breaks
* Report when HMR is broken, it is currently silent

```[tasklist]
### Tasks
- [ ] https://github.com/web-infra-dev/rspack/issues/2255
- [ ] https://github.com/web-infra-dev/rspack/issues/4340
- [ ] https://github.com/web-infra-dev/rspack/issues/4341
- [ ] https://github.com/web-infra-dev/rspack/issues/3715
- [ ] https://github.com/web-infra-dev/rspack/issues/3883
- [ ] https://github.com/web-infra-dev/rspack/issues/4344
- [ ] https://github.com/web-infra-dev/rspack/issues/4348
- [ ] https://github.com/web-infra-dev/rspack/issues/4326
- [ ] https://github.com/web-infra-dev/rspack/issues/4321
- [ ] https://github.com/web-infra-dev/rspack/issues/4504
- [ ] https://github.com/web-infra-dev/rspack/issues/5082
- [ ] https://github.com/web-infra-dev/rspack/issues/4769
- [ ] https://github.com/web-infra-dev/rspack/issues/5619
- [ ] https://github.com/web-infra-dev/rspack/issues/5627
- [ ] https://github.com/web-infra-dev/rspack/issues/5632
- [ ] https://github.com/web-infra-dev/rspack/issues/5986
- [ ] https://github.com/web-infra-dev/rspack/issues/6051
```

**Comment by hyf0** [comment]
Context:

This the current design of error-handling in Rspack: https://github.com/web-infra-dev/rspack/discussions/548.

**Comment by hyf0** [comment]
We should first design good error data structures both for the rust and js sides, then we could start to improve the error handling on top of those data structures.

**Comment by hardfist** [comment]
need to add hint support for better error suggestions like https://github.com/webpack/webpack/issues/17122, cc @ScriptedAlchemy

**Comment by hardfist** [comment]
another thing drive me nuts is that when rspack panic all diagnostics is lost
