### ISSUE TITLE
[Tracking]:  Migration for `SplitChunksPlugin` tests

### ISSUE THREAD

**Issue by hyf0** [web-infra-dev/rspack#3503]
### What subject does this issue tracking?

Migrate tests at

- https://github.com/hyf0/webpack/blob/7c1cdda125b97568607e4784fd739348e0f9baef/test/configCases/split-chunks
- https://github.com/hyf0/webpack/blob/f1cb4825e48ba115747c2c3022ef3344c29e08f5/test/configCases/split-chunks-common

# [Subject]

```[tasklist]
### Tasks
- [ ] https://github.com/web-infra-dev/rspack/issues/3504
- [ ] https://github.com/web-infra-dev/rspack/issues/3505
- [ ] https://github.com/web-infra-dev/rspack/issues/3506
- [ ] https://github.com/web-infra-dev/rspack/issues/3507
```

## Ignored

- https://github.com/hyf0/webpack/blob/671ac29d462e75a10c3fdfc785a4c153e41e749e/test/configCases/split-chunks/issue-11513

Requires passing `object` to `maxSize`

# webpack-tests

```[tasklist]
### Tasks
- [ ] https://github.com/web-infra-dev/rspack/issues/3562
- [ ] https://github.com/web-infra-dev/rspack/issues/1653
- [ ] https://github.com/web-infra-dev/rspack/issues/3564
- [ ] https://github.com/web-infra-dev/rspack/issues/3565
- [ ] https://github.com/web-infra-dev/rspack/issues/3507
- [ ] https://github.com/web-infra-dev/rspack/issues/3504
```

**Comment by hardfist** [comment]
close for stale
