### ISSUE TITLE
[Tracking]: source manipulation based on `String`

### ISSUE THREAD

**Issue by underfin** [web-infra-dev/rspack#3533]
### What subject does this issue tracking?

# [Subject]

```[tasklist]
### Tasks
- [x] string replace
- [x] tree-shaking
- [x] rspack test
- [x] run fs project
- [x] disable source manipulation based on `Ast`
- [ ] https://github.com/web-infra-dev/rspack/issues/3553
- [ ] https://github.com/web-infra-dev/rspack/issues/3550
```
