### ISSUE TITLE
[Tracking]: HMR performance monitor

### ISSUE THREAD

**Issue by jerrykingxyz** [web-infra-dev/rspack#3593]
### What subject does this issue tracking?

# [Subject]

To avoid HMR performance degradation, we need
* add some tests before pr merge
* Generate hmr performance report on release

```[tasklist]
### Tasks
- [ ] discuss the implementation
- [ ] hmr performance ci
- [ ] generate hmr performance report
```
