### ISSUE TITLE
[Tracking]: Webpack Loader test cases

### ISSUE THREAD

**Issue by h-a-n-a** [web-infra-dev/rspack#3626]
### What subject does this issue tracking?

# cases/loaders

```[tasklist]
### Tasks
- [x] async
- [ ] coffee-loader
- [ ] context
- [x] css-loader
- [ ] emit-file
- [ ] import-module
- [ ] webpack-issue-2299
- [ ] webpack-issue-4959
- [ ] webpack-issue-10725
- [x] json-loader
- [x] less-loader
- [ ] module-description-file
- [ ] no-string
- [x] pug-loader
- [x] query(partially)
- [x] raw-loader
- [ ] resolve
- [ ] utils
```

# configCases/loaders

```[tasklist]
### Tasks
- [x] generate-ident
- [ ] hot-in-context
- [x] mode-default
- [x] mode-production
- [x] mode-development
- [x] mode-none
- [ ] webpack-issue-3320
- [ ] webpack-issue-9053
- [x] options(partially fixed)
- [ ] webpack-pr-14384
- [x] pre-post-loader
- [x] remaining-loader
- [ ] https://github.com/web-infra-dev/rspack/issues/4414
```
