### ISSUE TITLE
[Tracking]: Tracking the difference runtime result between Rspack and Webpack

### ISSUE THREAD

**Issue by hardfist** [web-infra-dev/rspack#4031]
### What subject does this issue tracking?

# [Runtime Diff]
![image](https://github.com/web-infra-dev/rspack/assets/8898718/f2885e4b-7461-441b-8afe-ef857e0930b1)

- [x] no 'use strict' in esm module codegen
- [x] #6402
![image](https://github.com/web-infra-dev/rspack/assets/8898718/717ce359-d436-4aed-acb0-85e9186ca4b2)

- [x] missing binding annotation for export esm variable
- [x] module codegen shouldn't be  transformed to es5 by default
- [x] instance of is translated to function by swc in rspack
- [x] 'use strict' optimization if all modules are strict module
- [ ] default export misalign
![image](https://github.com/web-infra-dev/rspack/assets/8898718/d30fc6ed-cb8f-4d8d-91cc-61e8f73d2173)
- [x] #4047
- [x] missing constPlugin cause import extra react module
![image](https://github.com/web-infra-dev/rspack/assets/8898718/30898fae-4783-4579-a0bd-7072ebd82b13)
- [x] #4118
