### ISSUE TITLE
[Tracking]: Oxc Resolver

### ISSUE THREAD

**Issue by Boshen** [web-infra-dev/rspack#4033]
### What subject does this issue tracking?

# [Subject]

Oxc resolver is mostly complete, this issue tracks Rspack's adoption.

Oxc resolver is currently 3 times faster than nodejs_resolver, and is intending to add built-in support tsconfig-paths with project references.

```[tasklist]
### Tasks
- [x] https://github.com/web-infra-dev/rspack/pull/3982
- [x] https://github.com/web-infra-dev/rspack/pull/4048
- [x] https://github.com/web-infra-dev/rspack/pull/4108
- [x] https://github.com/web-infra-dev/rspack/pull/4192
- [ ] https://github.com/web-infra-dev/rspack/issues/4211
```
