### ISSUE TITLE
Tracking issue for asset support 

### ISSUE THREAD

**Issue by h-a-n-a** [web-infra-dev/rspack#407]
**Checklist**

This is a checklist to track requirements for asset support

- [ ] ~~impl delayed job and shared code generation result~~
- [ ] ~~add buffer support for rspack-sources~~
- [ ] ~~replace string to rspack-sources~~
- [x] plugin asset

**Original RFC**
https://github.com/speedy-js/rspack/discussions/405
