### ISSUE TITLE
[Tracking]: Testing against webpack core tests

### ISSUE THREAD

**Issue by ahabhgk** [web-infra-dev/rspack#4327]
Rspack is running webpack tests to discover current implementations and functionalities misaligned with webpack.

Our goal is to maintain consistency with webpack as much as possible, but there are still some features that require discussion to determine whether or not to support them. These include APIs that have alternative ECMAScript standards or features that have high support costs but are used by very few people. This issue is meant to track these inconsistencies, and we will continue to improve test coverage and pass rates in the future.

We have already run some tests at the moment. Of course, we welcome your help in advancing the testing progress and discovering any issues. This may require a certain level of familiarity with webpack's code to identify the underlying causes of test failures.

The following are the steps to advance the testing progress:

1. Run `pnpm run build:cli:debug` or `pnpm run build:cli:release` to make sure you are on the latest build.
2. `cd webpack-test` and find a test that you want to run.
3. Make sure the `test.filter.js` under the test case is returning true.
4. Run `pnpm run test -- -t "test name"`, for example, if you want to run `webpack-test/cases/amd/define-needs-module`, you can use the following command `pnpm run test -- -t "amd define-needs-module"`
5. If it passes, then you can remove `test.filter.js` under the test case.
6. If it doesn't passes, then you need to find the reason why it failed, and make `test.filter.js` return a string that contain the reason, and it would be better to create a issue and use the link as the reason, for example `module.exports = () => {return "https://github.com/web-infra-dev/rspack/issues/4313"}`

**And the principle is not to modify the code of `webpack-test`'s test to make the test passes. Instead, focus on tracking all inconsistencies as much as possible.**

Here are some of the identified issues:

```[tasklist]
### Unsupported features
- [ ] https://github.com/web-infra-dev/rspack/issues/4313
- [ ] https://github.com/web-infra-dev/rspack/issues/4306
- [ ] https://github.com/web-infra-dev/rspack/issues/4304
- [ ] https://github.com/web-infra-dev/rspack/issues/3889
- [ ] https://github.com/web-infra-dev/rspack/issues/4350
- [ ] https://github.com/web-infra-dev/rspack/issues/4358
- [ ] https://github.com/web-infra-dev/rspack/issues/3346
- [ ] https://github.com/web-infra-dev/rspack/issues/4396
- [ ] https://github.com/web-infra-dev/rspack/issues/4427
- [ ] https://github.com/web-infra-dev/rspack/issues/4433
- [ ] https://github.com/web-infra-dev/rspack/issues/4445
- [ ] https://github.com/web-infra-dev/rspack/issues/4446
- [ ] https://github.com/web-infra-dev/rspack/issues/3823
- [ ] https://github.com/web-infra-dev/rspack/issues/5254
- [ ] https://github.com/web-infra-dev/rspack/issues/5393
```

```[tasklist]
### Parser hook/Compile time evaluation
- [ ] https://github.com/web-infra-dev/rspack/issues/4300
- [ ] https://github.com/web-infra-dev/rspack/issues/4439
- [ ] https://github.com/web-infra-dev/rspack/issues/4424
```

```[tasklist]
### TreeShaking/SideEffects
- [ ] https://github.com/web-infra-dev/rspack/issues/4426
- [ ] https://github.com/web-infra-dev/rspack/issues/4336
```

```[tasklist]
### SplitChunks
- [ ] https://github.com/web-infra-dev/rspack/issues/4331
- [ ] https://github.com/web-infra-dev/rspack/issues/4333
- [ ] https://github.com/web-infra-dev/rspack/issues/4334
- [ ] https://github.com/web-infra-dev/rspack/issues/4335
```

```[tasklist]
### CSS
- [ ] https://github.com/web-infra-dev/rspack/issues/4431
```

```[tasklist]
### Sourcemap
- [ ] https://github.com/web-infra-dev/rspack/issues/5394
```

```[tasklist]
### Output
- [ ] https://github.com/web-infra-dev/rspack/issues/5395
```

```[tasklist]
### Node API
- [ ] https://github.com/web-infra-dev/rspack/issues/4398
- [ ] https://github.com/web-infra-dev/rspack/issues/3738
- [ ] https://github.com/web-infra-dev/rspack/issues/4442
```

```[tasklist]
### Dependency/Codegen
- [ ] https://github.com/web-infra-dev/rspack/issues/4325
- [ ] https://github.com/web-infra-dev/rspack/issues/4440
- [ ] https://github.com/web-infra-dev/rspack/issues/4421
- [ ] https://github.com/web-infra-dev/rspack/issues/4324
- [ ] https://github.com/web-infra-dev/rspack/issues/4323
- [ ] https://github.com/web-infra-dev/rspack/issues/4401
- [ ] https://github.com/web-infra-dev/rspack/issues/4118
- [ ] https://github.com/web-infra-dev/rspack/issues/4441
- [ ] https://github.com/web-infra-dev/rspack/issues/4443
- [ ] https://github.com/web-infra-dev/rspack/issues/5596
```

```[tasklist]
### Errors/Warnings inconsistent
- [ ] https://github.com/web-infra-dev/rspack/issues/4332
- [ ] https://github.com/web-infra-dev/rspack/issues/4326
- [ ] https://github.com/web-infra-dev/rspack/issues/4349
- [ ] https://github.com/web-infra-dev/rspack/issues/4318
- [ ] https://github.com/web-infra-dev/rspack/issues/4348
- [ ] https://github.com/web-infra-dev/rspack/issues/4419
- [ ] https://github.com/web-infra-dev/rspack/issues/4347
```

```[tasklist]
### ContextModule
- [ ] https://github.com/web-infra-dev/rspack/issues/4420
- [ ] https://github.com/web-infra-dev/rspack/issues/4397
- [ ] https://github.com/web-infra-dev/rspack/issues/4429
- [ ] https://github.com/web-infra-dev/rspack/issues/4329
- [ ] https://github.com/web-infra-dev/rspack/issues/4315
- [ ] https://github.com/web-infra-dev/rspack/issues/4328
- [ ] https://github.com/web-infra-dev/rspack/issues/4305
- [ ] https://github.com/web-infra-dev/rspack/issues/4450
```

```[tasklist]
### Panic bug
- [ ] https://github.com/web-infra-dev/rspack/issues/3180
- [ ] https://github.com/web-infra-dev/rspack/issues/5573
- [ ] https://github.com/web-infra-dev/rspack/issues/5574
- [ ] https://github.com/web-infra-dev/rspack/issues/5576
- [ ] https://github.com/web-infra-dev/rspack/issues/5577
- [ ] https://github.com/web-infra-dev/rspack/issues/5578
- [ ]  https://github.com/web-infra-dev/rspack/issues/5579
- [ ] https://github.com/web-infra-dev/rspack/issues/5580
```

```[tasklist]
### Test Infrastructure
- [ ] https://github.com/web-infra-dev/rspack/issues/5582
```

**Comment by chenjiahan** [comment]
I will close this tracking issue since we have a new tracking issue for webpack test cases: https://github.com/web-infra-dev/rspack/issues/8445

**Comment by chenjiahan** [comment]
I closed this tracking issue since we have a new tracking issue for webpack test cases: https://github.com/web-infra-dev/rspack/issues/8445
