### ISSUE TITLE
Tracking: Align error messages with Webpack

### ISSUE THREAD

**Issue by h-a-n-a** [web-infra-dev/rspack#4341]
## Common

```[tasklist]
- [ ] https://github.com/web-infra-dev/rspack/pull/4892
- [ ] https://github.com/web-infra-dev/rspack/pull/5020
- [ ] https://github.com/web-infra-dev/rspack/pull/5062
- [ ] https://github.com/web-infra-dev/rspack/pull/5049
- [ ] https://github.com/web-infra-dev/rspack/pull/4924
- [ ] https://github.com/web-infra-dev/rspack/issues/1823
- [ ] https://github.com/web-infra-dev/rspack/pull/5084
- [ ] https://github.com/web-infra-dev/rspack/pull/5363
```

## Panic handling

```[tasklist]
- [ ] https://github.com/web-infra-dev/rspack/pull/4940
- [ ] https://github.com/web-infra-dev/rspack/pull/4848

```

## Module

```[tasklist]
- [ ] https://github.com/web-infra-dev/rspack/pull/5062
- [ ] https://github.com/web-infra-dev/rspack/pull/5286
```

## Module factory
```[tasklist]
- [ ] https://github.com/web-infra-dev/rspack/pull/5084
- [ ] https://github.com/web-infra-dev/rspack/pull/5124
- [ ] https://github.com/web-infra-dev/rspack/pull/5178
- [ ] https://github.com/web-infra-dev/rspack/pull/5139
```

**Comment by chenjiahan** [comment]
Need the following improvements:

- Use color to distinguish important and not important informations
- Provide correct codeframe
- Provide better typography

**Comment by chenjiahan** [comment]
bump
