### ISSUE TITLE
Tracking issue of asset support 

### ISSUE THREAD

**Issue by h-a-n-a** [web-infra-dev/rspack#435]
Checklists: 
- [X] impl plugin asset https://github.com/speedy-js/rspack/pull/413  https://github.com/speedy-js/rspack/pull/427 
- [X] support custom asset filename https://github.com/speedy-js/rspack/pull/428
- [X] support buffer https://github.com/speedy-js/rspack/pull/426
- [x] #453
- [x] #452
- [x] #451
- [x] ~~enhanced mechanism to handle module types which don't have any ASTs (related to reuseAST hint) cc @hardfist~~ (removed for favoring of webpack's reuseAST model)
