### ISSUE TITLE
[Tracking]: Memory leak

### ISSUE THREAD

**Issue by h-a-n-a** [web-infra-dev/rspack#4409]
### What subject does this issue tracking?

```[tasklist]
### Tasks
- [ ] https://github.com/web-infra-dev/rspack/issues/3169
- [ ] https://github.com/web-infra-dev/rspack/issues/4410
- [ ] https://github.com/web-infra-dev/rspack/issues/4411
```

**Comment by VanderSP** [comment]
https://github.com/web-infra-dev/rspack/issues/6487

It always happened to me since early age
