### ISSUE TITLE
[Tracking]: Wasm support and support run on stackblitz and WebContainer

### ISSUE THREAD

**Issue by hardfist** [web-infra-dev/rspack#4550]
### What subject does this issue tracking?

# [Subject]

```[tasklist]
### Tasks
- [ ] napi-rs wasm support
- [ ] build Rspack wasm target
- [ ] integrate Rspack into Stackblitz
- [ ] run stackblitz example on rspack website
```

**Comment by hardfist** [comment]
this is for someone who is interested in wasm integration

**Comment by hussain-s6** [comment]
Any plans for this support? I believe it is required for Rspack/Rsbuild to work inside Stackblitz (as you have already mentioned inside this ticket: #2986 )
I will try to run Rsbuild inside codesandbox but I much prefer Stackblitz as it's much faster and has much better "free" version.

**Comment by hardfist** [comment]
we will support wasm but it's low priority

**Comment by busy-mango** [comment]
> we will support wasm but it's low priority

I hope this feature comes sooner rather than later

**Comment by chenjiahan** [comment]
Update: https://x.com/ScriptedAlchemy/status/1805779131365490778

![image](https://github.com/web-infra-dev/rspack/assets/7237365/3edc1d3e-38a5-4e68-a585-585ec14324f1)

**Comment by hardfist** [comment]
close in favor of #9134
