### ISSUE TITLE
[Tracking]: Improve Rspack Developer's Developer Experience 

### ISSUE THREAD

**Issue by hardfist** [web-infra-dev/rspack#4587]
### What subject does this issue tracking?

# [DX for Rspack Developer]
As we develop Rspack daily, we met some problems which limits our developer's development efficiency, let's track and progressive improve it
```[tasklist]
### Tasks
- [ ] Too much boilerplate code for adding new napi-rs binding especially when adding function api
- [ ] Js side Unit Testing is hard to debug separately
- [ ] Too much flaky test in daily CI jobs( release nightly failed every day)
- [ ] Hard to Mixed Debug a specific Jest case(vscode not supports interactive select debug case)
- [ ] generated binding.d.ts is unstable, which cause unnecessary new changed file
- [ ] Just a thought: there are lots of abstraction heavily depend on dynamic object upcast/downcast, Dependency <-> ModuleDependency <-> HarmonyImportDependency <-> HarmonyImportSpecifierDependency, Module <-> NormalModule (<-> CssModule), InitFragment <-> HarmonyExportInitFragment, it would be great if we can provide an efficient solution for this
```

**Comment by chenjiahan** [comment]
The pnpm version is not limited by `engine`, some pull request cause the lock file to change a lot.

![image](https://github.com/web-infra-dev/rspack/assets/7237365/a68de517-0ff1-460b-9312-d22f4a95ad2a)

For exmaple: https://github.com/web-infra-dev/rspack/pull/4573/files#diff-32824c984905bb02bc7ffcef96a77addd1f1602cff71a11fbbfdd7f53ee026bbL76

**Comment by hardfist** [comment]
Normalize Test Runner process and make it extensible for adding new test type

**Comment by msdlisper** [comment]
hi~ @hardfist , I think this problem #4609  can be looked at together, some package versions do not specify the code can not run, which too affect the development experience

**Comment by msdlisper** [comment]
hi~ @hardfist Why don't we try @swc/jest to speed up our testing ? although not much code is currently compiled with babel, which will slow down as more use cases are added :)

**Comment by hardfist** [comment]
> hi~ @hardfist Why don't we try @swc/jest to speed up our testing ? although not much code is currently compiled with babel, which will slow down as more use cases are added :)

No particular reason, @msdlisper can you give it a try, if it works we would like to change to @swc/jest
