### ISSUE TITLE
Tracking test case from webpack for CSS Module

### ISSUE THREAD

**Issue by IWANABETHATGUY** [web-infra-dev/rspack#471]
- [ ] asset-modules
- [ ] at-import-in-the-entry
- [x] #529
- [ ] at-import-layer
- [ ] at-import-supports
- [ ] at-media
- [ ] auxiliary-assets
- [ ] base-uri
- [ ] base-uri-in-entry
- [ ] chunkFilename
- [ ] chunkFilename-as-function
- [ ] chunkFilename-fullhash
- [ ] commonjs-module-syntax
- [ ] composes-async
- [ ] content-entries-with-same-import
- [ ] contenthash
- [ ] contenthash-1
- [ ] contenthash-multiple-entries
- [ ] custom-loader-with-new-url-and-public-path
- [ ] custom-loader-with-new-url-and-public-path-1
- [ ] custom-loader-with-new-url-and-public-path-auto
- [ ] custom-loader-with-new-url-and-public-path-default-auto
- [ ] dependOn
- [ ] dependOn-multiple-files-per-entry
- [ ] devtool-source-map
- [ ] devtool-source-map-from-loaders
- [ ] devtool-source-map-no-source-maps-from-loaders
- [ ] es-module-concatenation
- [ ] es-module-concatenation-modules
- [ ] es-module-syntax
- [ ] es-named-export
- [ ] es-named-export-output-module
- [ ] experimentalUseImportModule-false
- [ ] experimentalUseImportModule-true
- [ ] experimentalUseImportModule-undefined
- [ ] export-only-locals
- [ ] export-only-locals-and-es-named-export
- [ ] export-only-locals-commonjs
- [ ] file-loader
- [ ] filename-as-function
- [ ] filename-without-template
- [ ] filename-with-template
- [ ] hmr
- [x] #530
- [ ] ignoreOrder
- [ ] ignoreOrderFalse
- [ ] ignoreOrderFalseWithoutGoodChunks
- [ ] ignore-other-loaders
- [ ] ignore-other-loaders-2
- [ ] insert-function
- [ ] insert-string
- [ ] insert-undefined
- [ ] js-hash
- [ ] moduleFilenameMutableFilename
- [ ] multiple-compiler
- [ ] multiple-entry
- [ ] multiple-themes-async-loading
- [ ] multiple-themes-async-loading-with-default-light
- [ ] new-url
- [ ] no-identifier
- [ ] no-runtime
- [ ] no-source-map
- [ ] output-module
- [ ] pathinfo
- [ ] pathinfo-devtool-source-map
- [ ] publicpath-absolute-url
- [ ] publicpath-absolute-url-1
- [ ] publicpath-absolute-url-2
- [ ] publicpath-absolute-url-3
- [ ] publicpath-absolute-url-4
- [ ] publicpath-absolute-url-5
- [ ] publicpath-absolute-url-6
- [ ] publicpath-auto
- [ ] publicpath-auto-2
- [ ] publicpath-auto-3
- [ ] publicpath-auto-4
- [ ] publicpath-default-auto
- [ ] publicpath-empty-string
- [ ] publicpath-function
- [ ] publicpath-function-2
- [ ] publicpath-loader-auto
- [ ] publicpath-path-relative
- [ ] publicpath-path-relative-1
- [ ] publicpath-path-relative-2
- [ ] publicpath-path-relative-3
- [ ] publicpath-path-relative-4
- [ ] publicpath-path-relative-5
- [ ] publicpath-path-relative-6
- [ ] publicpath-path-relative-7
- [ ] runtime
- [ ] serializingBigStrings
- [ ] simple-async-load-css-fallback
- [ ] simple-async-source-map
- [ ] simple-css-modules-mode-global
- [ ] simple-css-modules-mode-local
- [ ] simple-css-modules-mode-local-output-module
- [ ] simple-css-modules-mode-pure
- [ ] source-map
- [ ] split-chunks
- [ ] split-chunks-all
- [ ] split-chunks-based-on-entry
- [ ] split-chunks-based-on-entry-with-common-chunk
- [ ] split-chunks-based-on-entry-with-common-chunk-and-inside-dir
- [ ] split-chunks-based-on-entry-with-common-in-each-chunk
- [ ] split-chunks-no-vendor
- [ ] split-chunks-recursiveIssuer
- [ ] split-chunks-single
