### ISSUE TITLE
Tracking issue of HTML Plugin

### ISSUE THREAD

**Issue by byted-meow** [web-infra-dev/rspack#494]
Checklist:

- [x] Implements the HTML Plugin

Blocked by:

- [x] node binding and plugin config
- [x] a new process_assets hook in plugin driver
- [x] a better assets or compilation.entrypoints (for list of entry names, info, emitted chunk files)

...and maybe blocked by:

- [ ] asset.get_hash
- [ ] rename asset
- [ ] cache

Test Cases:

- [x] Parse template HTML to AST
- [x] Retrieve entries from core
- [x] Append entries to HTML files, with configuration support

Future Improvements:

- [ ] Support inject args to html files, such as, compile EJS-like HTML template
- [x] Support Plugins, such as subresource integrity plugin
