### ISSUE TITLE
Tracking issue for Runtime PR optimizing

### ISSUE THREAD

**Issue by liuliudada-w** [web-infra-dev/rspack#503]
There is some unresolved problem in the https://github.com/speedy-js/rspack/pull/473. This issue will tarck them.

- [x] improve the target options
- [x] replace macro to function in the runtime generation
- [ ] move JS Runtime Code to rspack_plugin_javascript
- [ ] move CSS Runtime Code to rspack_plugin_css
