### ISSUE TITLE
[Tracking]: improve performance profile DX

### ISSUE THREAD

**Issue by hardfist** [web-infra-dev/rspack#5074]
### What subject does this issue tracking?
It's not easy to do performance profile for Rspack now especially for HMR scenario, we miss lots of functionality right now  for better support of performance analysis

```[tasklist]
### Tasks
- [ ] https://github.com/web-infra-dev/rspack/issues/5071
- [ ] combine tracing in rust side and js side
- [ ] async job performance analysis between threads
```

Related Resource
* https://github.com/iamakulov/devtools-perf-features#timeline-event-initiators
