### ISSUE TITLE
Tracking issue of Loader

### ISSUE THREAD

**Issue by h-a-n-a** [web-infra-dev/rspack#516]
> Tracking issue for loader discussion https://github.com/speedy-js/rspack/discussions/514

## Stage 1

Checklist:
- [x] #532
- [x] #519
- [x] #520
- [x] #573

## Stage2

Checklist:

- [x] #598

**Virtual module**
- [x] hook `read_resource`(https://github.com/speedy-js/rspack/pull/615)
- [x] #599
- [ ] Support scheme parsing and loading for core and loader-runner (via plugin system)
- [ ] Support data imports for `text/javascript`

**Enhanced loader context**
- [x] #595
- [x] #596
- [x] #597

**Node binding**
- [x] Canonicalize `module.rules` structure (implemented in https://github.com/speedy-js/rspack/pull/606)
- [x] Support JS Loader API `this.getOptions`(implemented in https://github.com/speedy-js/rspack/pull/606)
- [ ] Split `buffer` passing into a new parameter

## Unresolved questions
- [x] #574
- [x] #592
