### ISSUE TITLE
[Tracking]: moving examples to separate repo

### ISSUE THREAD

**Issue by hardfist** [web-infra-dev/rspack#5295]
### What subject does this issue tracking?
Consider move examples to https://github.com/rspack-contrib/rspack-examples which brings the following benifits
* Reduce ci time in rspack repo(install time & build time)
* Lower the threshold for contribution
* Put rspack ecosystem( rspack、rspress、rsbuild) together for reference for users
```[tasklist]
### Tasks
- [x] create rspack-examples repo
- [x] move examples to rspack-examples
- [x] integrate rspack-examples in ecosystem ci https://github.com/web-infra-dev/rspack-ecosystem-ci/issues/25
- [ ] https://github.com/web-infra-dev/rspack/pull/5296
- [ ] move webpack examples to rspack and add more bundler only example https://github.com/rspack-contrib/rspack-examples/issues/12
- [x] link in readme https://github.com/web-infra-dev/rspack/pull/5297
- [x] update documentation link to new repo https://github.com/web-infra-dev/rspack-website/pull/604
```

**Comment by faga295** [comment]
https://github.com/web-infra-dev/rspack/blob/53ae30d7f1fd41dbd736ccfc28b840f1c4ec4743/.vscode/launch.json#L47-L79 Some configurations related to `examples` should also be removed

**Comment by Boshen** [comment]
Apparently webpack-examples unit tests are manageable, see https://github.com/web-infra-dev/rspack/pull/5376

I've also created an issue at rspack-examples https://github.com/rspack-contrib/rspack-
