### ISSUE TITLE
[Tracking]: Stabilizing Node API

### ISSUE THREAD

**Issue by h-a-n-a** [web-infra-dev/rspack#5822]
### What subject does this issue tracking?

This issue tracks the Node APIs for JS users.

## Goals

**1. Correctness** Node API in v1.0 stable rspack should be fully tested. This includes arguments that passed to the JS side, and the return value passed back to the Rust side should also be included.

**2. Deprecations** APIs that are no longer supported in v1.0 well be kindly removed. This includes BREAKING CHANGES to the current codebase. This will be well-documented.

**3. Documentation** rspack-website still lacks of Node API doc. related: https://github.com/web-infra-dev/rspack-website/issues/629

## Tasks

```[tasklist]
### Tasks
- [ ] https://github.com/web-infra-dev/rspack/pull/6448
- [ ] https://github.com/web-infra-dev/rspack/pull/6505
- [ ] https://github.com/web-infra-dev/rspack/pull/6859
```

**Comment by hardfist** [comment]
seem resolved
