### ISSUE TITLE
[Tracking]: refactor make stage to support incremental build architecture

### ISSUE THREAD

**Issue by jerrykingxyz** [web-infra-dev/rspack#6281]
### What subject does this issue tracking?

# [Subject]

```[tasklist]
### Tasks
- [x] https://github.com/web-infra-dev/rspack/pull/6004
- [ ] https://github.com/web-infra-dev/rspack/pull/6258
- [x] extract MakeArtifact and update make to pure function
```

**Comment by hardfist** [comment]
this seems resolved ? @jerrykingxyz
