### ISSUE TITLE
[Tracking]: Rspack v1.0

### ISSUE THREAD

**Issue by chenjiahan** [web-infra-dev/rspack#6689]
Track progress of Rspack 1.0 release.

## Schedule

Here is the planned schedule, which may be adjusted according to the progress of the tasks.

- **Rspack 1.0 alpha**: June W4
- **Rspack 1.0 beta**: July W2
- **Rspack 1.0 rc**: July W3
- **Rspack 1.0 stable**: July W4

> Ref: [Rspack v1.0 Release Plan](https://github.com/web-infra-dev/rspack/discussions/6315).

## Stabilizing API

Stabilizing API and make the core lean.

```[tasklist]
### Tasks
- [ ] https://github.com/web-infra-dev/rspack/issues/5822
- [ ] https://github.com/web-infra-dev/rspack/issues/5821
- [ ] https://github.com/web-infra-dev/rspack/issues/4327
- [ ] https://github.com/web-infra-dev/rspack/issues/5781
- [x] Remove rspackExperiments.emotion https://github.com/web-infra-dev/rspack/pull/6862
- [x] Remove rspackExperiments.relay https://github.com/web-infra-dev/rspack/pull/6862
- [x] Remove rspackExperiments.styledComponents https://github.com/web-infra-dev/rspack/pull/6862
- [x] Switch `experiments.css` to false by default @JSerFeng
- [x] Enable concatmodulePlugin by default in production @JSerFeng
- [x] Align default configuration with webpack @Symind
- [x] Remove resolve.tsConfigPath
- [x] Publish `rspackExperiments.preact` as SWC WASM plugin
```

> See also: https://github.com/web-infra-dev/rspack/discussions/6626

## Key Features

```[tasklist]
### Tasks
- [x] Integrate Lightning CSS an optional CSS minimizer @ahabhgk
- [x] Make lightningcss as the default CSS minimizer and remove `swc_css`  @ahabhgk
- [ ] https://github.com/web-infra-dev/rspack/issues/4823
```

## Document

Enhance the readability and accessibility of the Rspack documentation by eliminating outdated sections, incorporating new features, and preparing for the release of Rspack 1.0.

```[tasklist]
### Tasks
- [x] Set up documentation CI workflows
- [x] Implement a Git hook to automatically check documentation upon committing changes
- [x] Create a documentation contribution guide
- [x] Guide - Reorganize the table of contents for better navigation
- [x] Guide - Add the Languages Section
- [x] Guide - Revise the `Getting started` content to improve user experience
- [x] Guide - Remove obsolete information in the Features section and add details on new features
- [x] API - Introduce a new chapter for Node.js API
- [x] API - Reorganize the table of contents for better navigation
- [x] API - Clear out-of-date content and update with new features
- [x] Config - Separate the plugins list into its own dedicated section
- [ ] Config - Reorganize the table of contents for better navigation
- [x] Config - Discard outdated information and integrate new feature documentation
- [x] Plugin - Discard outdated information and integrate new feature documentation
- [ ] Developer Guide - Detail the tracing specification
- [x] Developer Guide - Guide on writing plugins in Rust
- [x] Developer Guide - Testing section
- [ ] Others - Automate documentation processes
```

## Announcement

```[tasklist]
### Tasks
- [x] Announcing Rspack v1.0 Alpha
- [x] Announcing Rspack v1.0 @All
- [ ] Announcing Rsbuild v1.0 @chenjiahan @9aoy
```
