### ISSUE TITLE
[Tracking]: Dependencies related governance [JS/pnpm] [Rust/Cargo]

### ISSUE THREAD

**Issue by SoonIter** [web-infra-dev/rspack#7156]
## Summary

Since Rspack contains a large number of phantom dependency problems, which is not conducive to developers, we need to govern the dependencies in both js and Rust sides.

### benefits

1. more stable CI test and e2e results 
2. more readable dependencies relationship and easier to update the deps version
3. this is a pre-task for https://github.com/web-infra-dev/rspack/pull/6323, better and simple dependencies graph will enhance the install speed

```[tasklist]
### Tasks
- [ ] https://github.com/web-infra-dev/rspack/pull/7094
- [ ] https://github.com/web-infra-dev/rspack/pull/7178
- [x] ci: `.pnpm/node_modules/<MODULE>/node_modules/dep_name` Snapshot serializer https://github.com/web-infra-dev/rspack/pull/8137
- [ ] https://github.com/web-infra-dev/rspack/pull/7130
- [ ] https://github.com/web-infra-dev/rspack/pull/6323
- [ ] #7208
- [ ] https://github.com/web-infra-dev/rspack/issues/7341
- [ ] #7403
- [ ] https://github.com/web-infra-dev/rspack/pull/7211
- [ ] https://github.com/web-infra-dev/rspack/pull/7235
- [x] Update the strategy of renovate in JS side https://github.com/web-infra-dev/rspack/pull/6429 https://github.com/web-infra-dev/rspack/pull/8294
- [x] Update the strategy of renovate in Rust side https://github.com/web-infra-dev/rspack/pull/6596 https://github.com/web-infra-dev/rspack/pull/8294
- [ ] Upgrade to pnpm9.5 to use "catelog:" protocol https://pnpm.io/catalogs (pending by renovate support https://github.com/renovatebot/renovate/issues/30079 ) https://github.com/web-infra-dev/rspack/pull/7065
```

**Comment by SoonIter** [comment]
It should be emphasized that we have a killer tool for phantom dependencies. https://github.com/chengcyber/scan-deps

https://github.com/web-infra-dev/rspack/pull/7178
`npx scan-deps --directory alert,debug,meta,release,test --extension ts,jsx,tsx,cjs,mjs,js --debug`

**Comment by SoonIter** [comment]
https://github.com/web-infra-dev/rspack/pull/7638#issuecomment-2301666065

**Comment by SoonIter** [comment]
only one remaining task

- Upgrade to pnpm9.5 to use "catelog:" protocol https://pnpm.io/catalogs (pending by renovate support https://github.com/renovatebot/renovate/issues/30079

close this first, we can consider it in the future
