### ISSUE TITLE
[Tracking]: JS -> TS refactor the remaining .js file to .ts

### ISSUE THREAD

**Issue by SoonIter** [web-infra-dev/rspack#7225]
### What subject does this issue tracking?

# JS -> TS

1. refactor the remaining .js file to .ts
2. remove all ts-expect-error
3. use typescript rather than JSDocs

https://github.com/web-infra-dev/rspack/issues/4640

```[tasklist]
### Tasks
- [ ] https://github.com/web-infra-dev/rspack/pull/7132
- [ ] https://github.com/web-infra-dev/rspack/pull/7136
- [ ] packages/rspack/src/ModuleTypeConstants.js & packages/rspack/src/Template.js
- [ ] packages/rspack/src/lib
- [ ] packages/rspack/src/config
- [ ] packages/rspack/src/util
- [ ] packages/rspack/src/loader-runner
- [ ] packages/rspack/src/builtin-plugin/css-extract/hmr
- [ ] packages/rspack-dev-server/src/ansiHTML.js
```

**Comment by SoonIter** [comment]
A very huge task, pr welcome~ :D

**Comment by SoonIter** [comment]
Use https://github.com/alexcanessa/typescript-coverage-report to count the typescript coverage 

## Before

<img width="400" alt="image" src="https://github.com/user-attachments/assets/318d524a-b46a-48b8-8139-4977d8982fe7">

## After #7289 

Still remaining some ts files

<img width="400" alt="image" src="https://github.com/user-attachments/assets/7f1f6e7a-e991-4aee-916a-46affa00a8da">

our goal is reach >= 97%, so pr also welcome

**Comment by wxiaoyun** [comment]
I will work on src/stats/StatsFactory.ts @shulaoda

**Comment by shulaoda** [comment]
> I will work on src/stats/StatsFactory.ts @shulaoda

I am working on `src/logging/truncateArgs.ts` 👀

**Comment by wxiaoyun** [comment]
Thanks for leaving utils/webpack 
Please let me work on it ❤️

**Comment by wxiaoyun** [comment]
I will work on `src/node/nodeConsole.ts` as well :heart:

**Comment by SoonIter** [comment]
after #7437

<img width="500" alt="image" src="https://github.com/user-attachments/assets/84920338-f302-4098-be09-9e9e190a1581">

our type coverage reach 95%, any pull request to increase type coverage is acceptable.

### type coverage contribution guide

1. run `pnpm install`
2. run `pnpm run type-coverage`
3. view files with low type coverage to contribute

**Comment by shulaoda** [comment]
> ### type coverage contribution guide
> 1. run `pnpm install`
> 2. run `pnpm run type-coverage`
> 3. view files with low type coverage to contribute

Should we add a script in `package.json`?

**Comment by SoonIter** [comment]
> Should we add a script in `package.json`?

Sorry, updated with `npx  typescript-coverage-report`

**Comment by shulaoda** [comment]
> Hey @SoonIter Still relevant to increase the type coverage for some of the files mentioned?

Welcome, try to do it.

**Comment by SoonIter** [comment]
> Hey @SoonIter Still relevant to increase the type coverage for some of the files mentioned?

yeah, pr welcome

**Comment by pawel-twardziak** [comment]
Is there anything left to work on here? :)

**Comment by SoonIter** [comment]
> Is there anything left to work on here? :)

Yeah, we can increase the type coverage according to https://github.com/web-infra-dev/rspack/issues/7225#issuecomment-2268319951

**Comment by SoonIter** [comment]
this issues is closed, but any pr that increases the type coverage is acceptable.
