### ISSUE TITLE
[Tracking]: Rsnext support

### ISSUE THREAD

**Issue by hardfist** [web-infra-dev/rspack#7269]
### What subject does this issue tracking?
Run Next.js on Rspack
https://github.com/ScriptedAlchemy/rsnext/pull/1/files# the progress is tracked here
```[tasklist]
### RsNext support
- [x] compilation.modules[i].blocks support
- [ ] https://github.com/web-infra-dev/rspack/issues/8406
- [x] support module.size as function
- [ ] issue and excluded used together have some problem https://github.com/ScriptedAlchemy/rsnext/pull/1/files#diff-84d995a20cdd661a5748456a06eefe6d6a7ea79501d500462e265d7ddba6742eL576
- [ ] support missing hook https://github.com/ScriptedAlchemy/rsnext/pull/1/files#diff-84d995a20cdd661a5748456a06eefe6d6a7ea79501d500462e265d7ddba6742eL576
- [x] support compilation.entries
- [ ] support moduleGraph.getModule
- [x] support seal hook
- [ ] moduleGraph api(getresolvedModule,getIssue,getExportsInfo,getModule,getIncomingConnections,getParentModule,getOutgoingConnection)
- [ ] succeedEntry and failedEntry Hook
```

**Comment by omar391** [comment]
Why is this issue closed? Its seems there's some existing task.

**Comment by webbertakken** [comment]
https://github.com/ScriptedAlchemy/rsnext is archived.

There's an update here as well: https://github.com/module-federation/core/issues/3153#issuecomment-2982745135.
