### ISSUE TITLE
[Tracking]: better diagnostic report of tapable error

### ISSUE THREAD

**Issue by shulaoda** [web-infra-dev/rspack#7336]
### What subject does this issue tracking?

Related to #6051 

This is a huge and complex task, and it took me a long time to understand how to complete it. This task involves many dependency types, and I need to break them down and gradually cover them.

```[tasklist]
### Tasks
- [ ] https://github.com/web-infra-dev/rspack/pull/7337
- [ ] https://github.com/web-infra-dev/rspack/pull/7374
- [ ] https://github.com/web-infra-dev/rspack/pull/7871
- [x] HarmonyExportExpressionDependency、HarmonyExportHeaderDependency、HarmonyExportImportedSpecifierDependency、HarmonyImportSideEffectDependency、HarmonyImportSpecifierDependency
- [x] HarmonyAcceptDependency、HarmonyExportSpecifierDependency、ModuleArgumentDependency
- [ ] CommonJsExportRequireDependency、CommonJsExportsDependency、CommonJsFullRequireDependency、CommonJsRequireDependency、CommonJsSelfReferenceDependency、CommonJsRequireContextDependency
- [ ] CssComposeDependency、CssImportDependency、CssLocalIdentDependency、CssUrlDependency
- [ ] WebpackIsIncludedDependency、PureExpressionDependency
- [ ] TODO: Others...
```
