### ISSUE TITLE
[Tracking]: migrate development workflow to just

### ISSUE THREAD

**Issue by hardfist** [web-infra-dev/rspack#7516]
### What subject does this issue tracking?

# [migrate development workflow to just]
## background
we may need some rust workflow(like rust api bump、release) in the future, which cause we may have js workflow and rust workflow together. Currently we use `./x` to manage js workflow but it seems not idea to use `./x` to manage rust workflow. so we're considering migrate the whole development workflow to just + js-script + xtask.
## Design
our daily workflow actually contain two parts
* task implementation: task like publish | bump | debug | test and so on 
* task orchestra: how to orchestra task like run bump first and then run publish
just is good at task management and xtask is good at writing task using rust
so we  use just to do task orchestra and use js script and xtask to write task implementation.

```[tasklist]
### Tasks
- [ ] migrate current task orchestra in ./x to just
- [ ] update cicd to just command
- [ ] update contribute develop guide to just command
- [ ] remove `./x` and `./x.mjs`
- [ ] implement rust workflow (rust api release, doc generate) in just & xtask
```

**Comment by chenjiahan** [comment]
Should we alias the commands in `npm scripts` to just commands?

**Comment by hardfist** [comment]
> Should we alias the commands in `npm scripts` to just commands?

I think it's the reverse, just call `npm script` to do js task management

**Comment by hardfist** [comment]
> Some contributors may be used to using `npm scripts`, so how can we guide them?

provide detailed guide like this ? https://github.com/biomejs/biome/blob/main/CONTRIBUTING.md#install-the-required-tools 

> I think we can alias some basic commands to just. For example, alias pnpm run setup to just setup.

we can add some basic alias like `setup`, but when we have lots of tasks like https://github.com/biomejs/biome/blob/main/justfile, duplicate alias for all tasks seem not ideal

**Comment by shulaoda** [comment]
We can learn from this `xtask` case https://github.com/swc-project/swc/tree/main/xtask

**Comment by hardfist** [comment]
close since not gonna use just
