### ISSUE TITLE
[Tracking]: Stabilize Rust Public API

### ISSUE THREAD

**Issue by hardfist** [web-infra-dev/rspack#7689]
### What subject does this issue tracking?

# [Stabilize Rust Public API]

```[tasklist]
### Tasks
- [ ] Use Stable Rust
- [ ] Decouple with tokio runtime and support single thread mode
- [ ] Split rspack-core to rspack-kernel and rspack with register builtin plugin(lean core size and public api)
- [ ] Unify crate's public api (provide unified style api)
- [ ] Remove unnecessary unwrap | expect usage
- [ ] Clean rust dependencies
- [ ] reduce plugin crate number
```

**Comment by hardfist** [comment]
# Remove unnecessary unwrap | expect usage
1.  rspack follow's webpack implementation here assume dependencies[0] exists and is module_dependency
https://github.com/web-infra-dev/rspack/blob/main/crates/rspack_core/src/compiler/make/repair/factorize.rs#L237

**Comment by hardfist** [comment]
# Decouple with tokio and support single thread mode
Rspack's implementation is coupled with tokio now, which cause it hard to integrate with other library which may use other async runtime or use other tokio features
multi thread is also hard to support in some environment

**Comment by hardfist** [comment]
# Split rspack-core to rspack-kernel and rspack with register builtin plugin(lean core size and public api)
rspack-core has huge config api which makes it really hard to use, even we can reduce the config by default configuration, it still loads tons of builtin plugin which maybe not necessary for some environments.
