### ISSUE TITLE
Tracking issue of workarounds

### ISSUE THREAD

**Issue by h-a-n-a** [web-infra-dev/rspack#794]
> Tracking issue of **workarounds made to Rspack**, which is supported by Webpack but we haven't aligned fully with the implementations of which in Webpack.

### Module graph
- [X] Support module graph connection https://github.com/speedy-js/rspack/pull/836

### Module

- [X] Basic alignment https://github.com/speedy-js/rspack/pull/787
- [X] size https://github.com/speedy-js/rspack/pull/826
- [x] Raw Module 
- [x] External Module https://github.com/speedy-js/rspack/issues/1098

### Compilation

- [x] align with code generation
	- [x] move module build to compilation https://github.com/speedy-js/rspack/pull/836
	- [x] Extract code generation from render manifest https://github.com/speedy-js/rspack/pull/1091
- [x] https://github.com/speedy-js/rspack/issues/599

### Runtime
- [x] https://github.com/speedy-js/rspack/issues/1063
- [x] https://github.com/speedy-js/rspack/issues/1092

### Test
- [ ] Test cases should be typed with rspack/core options instead of Webpack configuration
- [ ] Add consistency test for rspack core and webpack types
- [x] #1034
