### ISSUE TITLE
Tracing Issue for rspack-provider

### ISSUE THREAD

**Issue by hardfist** [web-infra-dev/rspack#830]
This issue is used to track problems when implement  builder-rspack-provider which align with [builder-webpack-provider](https://github.com/modern-js-dev/modern.js/tree/main/packages/builder/builder-webpack-provider)
# Hooks
- [ ]  processAssets supports stage https://github.com/speedy-js/rspack/pull/771
- [ ]  support failed hook
- [ ]  support shouldEmit hook
- [x] #984

# Api
- [x] #985
- [ ] compiler.webpack.sources.RawSource
- [ ] compilation.outputOptions
- [ ] compilation.hash
- [ ] compiler.webpack.sources.SourceMapSource
- [ ] compiler.webpack.util.createHash

# Abilities
- [ ] progress bar implementation
