### ISSUE TITLE
Tracking issue of new node binding impl

### ISSUE THREAD

**Issue by h-a-n-a** [web-infra-dev/rspack#862]
## Main course
- [x] #863
- [x] #874
- [x] https://github.com/speedy-js/rspack/issues/879

## Related
- [x] https://github.com/speedy-js/rspack/issues/650
- [x] https://github.com/speedy-js/rspack/issues/779
