### ISSUE TITLE
Progressive implementing Tree-shaking

### ISSUE THREAD

**Issue by IWANABETHATGUY** [web-infra-dev/rspack#903]
- [x] Mark all `esm` exports, count unused exports (without side effects tracking)
   - [x] #904

      ```javascript
      // a.js
      import {test} from ''
      export function test() {
        
      }
      ```

   - [x] #911

- [x] #1040

      ```js
      import * as math from './math';
      
      console.log(math.add(2, 3));
      ```
- [x] module level side effects
- [ ] <del>dynamic import</del>
- [ ] commonJs 
- [ ] pure annotations
   ```js
   export const radius = 23;
   export const area = /*#__PURE__*/ calculateArea(radius);
   ```
- [ ] None es module tree shaking (CSS)
- [ ] chunk level tree-shaking

**Comment by chenjiahan** [comment]
I will close this issue as the new three shaking has been launched, and most issues have been resolved.

Feel free to reopen it if it is still needed.
